version: '2.1'

services:
  #Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

  #WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8977:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
      
  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8978:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: YOUR_PASSWORD
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
      